# 월별 순위 API

## 팀 이름
두산, 롯데, 삼성, 키움, 한화, KIA, KT, LG, NC, SSG

<br>

----

<br>

> 필요한 데이터 : Data/rank/*.csv

In [1]:
def teamRanking() :
    import pandas as pd
    # 사용자가 선택하는 값
    select_year = '2022'
    select_month = '04'
    team_name = '두산'

    # ------

    # 서버에서 불러와 원하는 값 추출
    team_df = pd.read_csv(f'./Data/rank/{team_name}_rank.csv')
    team_df.날짜 = pd.to_datetime(team_df.날짜)
    result_df = team_df[(team_df.날짜.dt.year == int(select_year)) & (team_df.날짜.dt.month == int(select_month))]
    result_df.loc[:, '날짜'] = result_df.날짜.astype(str)

    response = {}

    response['rank'] = []
    response['info'] = []

    for i,j in zip(result_df.to_dict()['날짜'].values(), result_df.to_dict()['순위'].values()) :
        result_dict = {
            '날짜' : i,
            '순위' : j
        }
        response['rank'].append(result_dict)


    for index in range(len(result_df.index)) :
        response['info'].append(result_df.loc[index, ['날짜', '총 경기수', '승리', '패배', '무승부', '승률', '게임차', '최근 10경기 전적', '연속 승패 현황', '홈 경기 전적', '원정 경기 전적']].to_dict())

    # return
    return response

In [2]:
result = teamRanking()

print(result)

{'rank': [{'날짜': Timestamp('2022-04-02 00:00:00'), '순위': 1}, {'날짜': Timestamp('2022-04-03 00:00:00'), '순위': 1}, {'날짜': Timestamp('2022-04-05 00:00:00'), '순위': 3}, {'날짜': Timestamp('2022-04-06 00:00:00'), '순위': 4}, {'날짜': Timestamp('2022-04-07 00:00:00'), '순위': 3}, {'날짜': Timestamp('2022-04-08 00:00:00'), '순위': 3}, {'날짜': Timestamp('2022-04-09 00:00:00'), '순위': 3}, {'날짜': Timestamp('2022-04-10 00:00:00'), '순위': 3}, {'날짜': Timestamp('2022-04-12 00:00:00'), '순위': 3}, {'날짜': Timestamp('2022-04-13 00:00:00'), '순위': 3}, {'날짜': Timestamp('2022-04-14 00:00:00'), '순위': 3}, {'날짜': Timestamp('2022-04-15 00:00:00'), '순위': 4}, {'날짜': Timestamp('2022-04-16 00:00:00'), '순위': 3}, {'날짜': Timestamp('2022-04-17 00:00:00'), '순위': 4}, {'날짜': Timestamp('2022-04-19 00:00:00'), '순위': 4}, {'날짜': Timestamp('2022-04-20 00:00:00'), '순위': 4}, {'날짜': Timestamp('2022-04-21 00:00:00'), '순위': 2}, {'날짜': Timestamp('2022-04-22 00:00:00'), '순위': 3}, {'날짜': Timestamp('2022-04-23 00:00:00'), '순위': 2}, {'날짜': Timestamp('2022-04-24 00:00:00'), '순위': 3}, {'날짜': Timestamp('2022-04-26 00:00:00'), '순위': 2}, {'날짜': Timestamp('2022-04-27 00:00:00'), '순위': 2}, {'날짜': Timestamp('2022-04-28 00:00:00'), '순위': 3}, {'날짜': Timestamp('2022-04-29 00:00:00'), '순위': 4}, {'날짜': Timestamp('2022-04-30 00:00:00'), '순위': 5}], 'info': [{'날짜': Timestamp('2022-04-02 00:00:00'), '총 경기수': 1, '승리': 1, '패배': 0, '무승부': 0, '승률': 1.0, '게임차': 0.0, '최근 10경기 전적': '1승0무0패', '연속 승패 현황': '1승', '홈 경기 전적': '1-0-0', '원정 경기 전적': '0-0-0'}, {'날짜': Timestamp('2022-04-03 00:00:00'), '총 경기수': 2, '승리': 2, '패배': 0, '무승부': 0, '승률': 1.0, '게임차': 0.0, '최근 10경기 전적': '2승0무0패', '연속 승패 현황': '2승', '홈 경기 전적': '2-0-0', '원정 경기 전적': '0-0-0'}, {'날짜': Timestamp('2022-04-05 00:00:00'), '총 경기수': 3, '승리': 2, '패배': 1, '무승부': 0, '승률': 0.667, '게임차': 1.0, '최근 10경기 전적': '2승0무1패', '연속 승패 현황': '1패', '홈 경기 전적': '2-0-1', '원정 경기 전적': '0-0-0'}, {'날짜': Timestamp('2022-04-06 00:00:00'), '총 경기수': 4, '승리': 2, '패배': 2, '무승부': 0, '승률': 0.5, '게임차': 2.0, '최근 10경기 전적': '2승0무2패', '연속 승패 현황': '2패', '홈 경기 전적': '2-0-2', '원정 경기 전적': '0-0-0'}, {'날짜': Timestamp('2022-04-07 00:00:00'), '총 경기수': 5, '승리': 3, '패배': 2, '무승부': 0, '승률': 0.6, '게임차': 2.0, '최근 10경기 전적': '3승0무2패', '연속 승패 현황': '1승', '홈 경기 전적': '3-0-2', '원정 경기 전적': '0-0-0'}, {'날짜': Timestamp('2022-04-08 00:00:00'), '총 경기수': 6, '승리': 4, '패배': 2, '무승부': 0, '승률': 0.667, '게임차': 2.0, '최근 10경기 전적': '4승0무2패', '연속 승패 현황': '2승', '홈 경기 전적': '3-0-2', '원정 경기 전적': '1-0-0'}, {'날짜': Timestamp('2022-04-09 00:00:00'), '총 경기수': 7, '승리': 4, '패배': 3, '무승부': 0, '승률': 0.571, '게임차': 3.0, '최근 10경기 전적': '4승0무3패', '연속 승패 현황': '1패', '홈 경기 전적': '3-0-2', '원정 경기 전적': '1-0-1'}, {'날짜': Timestamp('2022-04-10 00:00:00'), '총 경기수': 8, '승리': 5, '패배': 3, '무승부': 0, '승률': 0.625, '게임차': 3.0, '최근 10경기 전적': '5승0무3패', '연속 승패 현황': '1승', '홈 경기 전적': '3-0-2', '원정 경기 전적': '2-0-1'}, {'날짜': Timestamp('2022-04-12 00:00:00'), '총 경기수': 9, '승리': 6, '패배': 3, '무승부': 0, '승률': 0.667, '게임차': 3.0, '최근 10경기 전적': '6승0무3패', '연속 승패 현황': '2승', '홈 경기 전적': '3-0-2', '원정 경기 전적': '3-0-1'}, {'날짜': Timestamp('2022-04-13 00:00:00'), '총 경기수': 9, '승리': 6, '패배': 3, '무승부': 0, '승률': 0.667, '게임차': 3.5, '최근 10경기 전적': '6승0무3패', '연속 승패 현황': '2승', '홈 경기 전적': '3-0-2', '원정 경기 전적': '3-0-1'}, {'날짜': Timestamp('2022-04-14 00:00:00'), '총 경기수': 10, '승리': 7, '패배': 3, '무승부': 0, '승률': 0.7, '게임차': 2.5, '최근 10경기 전적': '7승0무3패', '연속 승패 현황': '3승', '홈 경기 전적': '3-0-2', '원정 경기 전적': '4-0-1'}, {'날짜': Timestamp('2022-04-15 00:00:00'), '총 경기수': 11, '승리': 7, '패배': 4, '무승부': 0, '승률': 0.636, '게임차': 3.5, '최근 10경기 전적': '6승0무4패', '연속 승패 현황': '1패', '홈 경기 전적': '3-0-3', '원정 경기 전적': '4-0-1'}, {'날짜': Timestamp('2022-04-16 00:00:00'), '총 경기수': 12, '승리': 8, '패배': 4, '무승부': 0, '승률': 0.667, '게임차': 3.5, '최근 10경기 전적': '6승0무4패', '연속 승패 현황': '1승', '홈 경기 전적': '4-0-3', '원정 경기 전적': '4-0-1'}, {'날짜': Timestamp('2022-04-17 00:00:00'), '총 경기수': 13, '승리': 8, '패배': 5, '무승부': 0, '승률': 0.615, '게임차': 4.5, '최근 10경기 전적': '6승0무4패', '연속 승패 현황': '1패', '홈 경기 전적': '4-0-4', '원정 경기 전적': '4-0-1'}, {'날짜': Timestamp('2022-04-19 00:00:00'), '총 경기수': 14, '승리': 8, '패배': 6, '무승부': 0, '승률': 0.571, '게임차': 4.5, '최근 10경기 전적': '6승0무4패', '연속 승패 현황': '2패', '홈 경기 전적': '4-0-4', '원정 경기 전적': '4-0-2'}, {'날짜': Timestamp('2022-04-20 00:00:00'), '총 경기수': 15, '승리': 9, '패배': 6, '무승부': 0, '승률': 0.6, '게임차': 4.5, '최근 10경기 전적': '6승0무4패', '연속 승패 현황': '1승', '홈 경기 전적': '4-0-4', '원정 경기 전적': '5-0-2'}, {'날짜': Timestamp('2022-04-21 00:00:00'), '총 경기수': 16, '승리': 10, '패배': 6, '무승부': 0, '승률': 0.625, '게임차': 4.5, '최근 10경기 전적': '6승0무4패', '연속 승패 현황': '2승', '홈 경기 전적': '4-0-4', '원정 경기 전적': '6-0-2'}, {'날짜': Timestamp('2022-04-22 00:00:00'), '총 경기수': 17, '승리': 10, '패배': 7, '무승부': 0, '승률': 0.588, '게임차': 4.5, '최근 10경기 전적': '6승0무4패', '연속 승패 현황': '1패', '홈 경기 전적': '4-0-5', '원정 경기 전적': '6-0-2'}, {'날짜': Timestamp('2022-04-23 00:00:00'), '총 경기수': 18, '승리': 11, '패배': 7, '무승부': 0, '승률': 0.611, '게임차': 3.5, '최근 10경기 전적': '6승0무4패', '연속 승패 현황': '1승', '홈 경기 전적': '5-0-5', '원정 경기 전적': '6-0-2'}, {'날짜': Timestamp('2022-04-24 00:00:00'), '총 경기수': 19, '승리': 11, '패배': 8, '무승부': 0, '승률': 0.579, '게임차': 4.5, '최근 10경기 전적': '5승0무5패', '연속 승패 현황': '1패', '홈 경기 전적': '5-0-6', '원정 경기 전적': '6-0-2'}, {'날짜': Timestamp('2022-04-26 00:00:00'), '총 경기수': 20, '승리': 12, '패배': 8, '무승부': 0, '승률': 0.6, '게임차': 4.5, '최근 10경기 전적': '5승0무5패', '연속 승패 현황': '1승', '홈 경기 전적': '6-0-6', '원정 경기 전적': '6-0-2'}, {'날짜': Timestamp('2022-04-27 00:00:00'), '총 경기수': 21, '승리': 13, '패배': 8, '무승부': 0, '승률': 0.619, '게임차': 4.0, '최근 10경기 전적': '6승0무4패', '연속 승패 현황': '2승', '홈 경기 전적': '7-0-6', '원정 경기 전적': '6-0-2'}, {'날짜': Timestamp('2022-04-28 00:00:00'), '총 경기수': 22, '승리': 13, '패배': 9, '무승부': 0, '승률': 0.591, '게임차': 4.0, '최근 10경기 전적': '5승0무5패', '연속 승패 현황': '1패', '홈 경기 전적': '7-0-7', '원정 경기 전적': '6-0-2'}, {'날짜': Timestamp('2022-04-29 00:00:00'), '총 경기수': 23, '승리': 13, '패배': 10, '무승부': 0, '승률': 0.565, '게임차': 5.0, '최근 10경기 전적': '5승0무5패', '연속 승패 현황': '2패', '홈 경기 전적': '7-0-7', '원정 경기 전적': '6-0-3'}, {'날짜': Timestamp('2022-04-30 00:00:00'), '총 경기수': 24, '승리': 13, '패배': 11, '무승부': 0, '승률': 0.542, '게임차': 6.0, '최근 10경기 전적': '5승0무5패', '연속 승패 현황': '3패', '홈 경기 전적': '7-0-7', '원정 경기 전적': '6-0-4'}]}

In [17]:
import pandas as pd
# 사용자가 선택하는 값
select_year = '2022'
select_month = '04'
team_name = '두산'

# ------

# 서버에서 불러와 원하는 값 추출
team_df = pd.read_csv(f'./Data/rank/{team_name}_rank.csv')
team_df.날짜 = pd.to_datetime(team_df.날짜)
result_df = team_df[(team_df.날짜.dt.year == int(select_year)) & (team_df.날짜.dt.month == int(select_month))]
result_df.loc[:, '날짜'] = result_df.날짜.astype(str)

In [27]:
# Last 10 Games Record , Streak Record , Home Games  Away Games

In [28]:
team_df

,date,teamname,rank,totalgames,win,loss,draw,winningrate,gamesbehind,10gamesrecord,streak,home,away
0,2022-04-02,두산,1,1,1,0,0,1.000,0.0,1승0무0패,1승,1-0-0,0-0-0
1,2022-04-03,두산,1,2,2,0,0,1.000,0.0,2승0무0패,2승,2-0-0,0-0-0
2,2022-04-05,두산,3,3,2,1,0,0.667,1.0,2승0무1패,1패,2-0-1,0-0-0
3,2022-04-06,두산,4,4,2,2,0,0.500,2.0,2승0무2패,2패,2-0-2,0-0-0
4,2022-04-07,두산,3,5,3,2,0,0.600,2.0,3승0무2패,1승,3-0-2,0-0-0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
383,2024-05-30,두산,2,58,32,24,2,0.571,3.0,6승1무3패,2승,19-1-10,13-1-14
384,2024-05-31,두산,3,59,32,25,2,0.561,3.0,6승0무4패,1패,19-1-11,13-1-14
385,2024-06-01,두산,4,60,32,26,2,0.552,4.0,5승0무5패,2패,19-1-12,13-1-14
386,2024-06-02,두산,4,61,32,27,2,0.542,4.0,4승0무6패,3패,19-1-13,13-1-14
387,2024-06-04,두산,4,62,33,27,2,0.550,3.0,4승0무6패,1승,19-1-13,14-1-14

In [20]:
import pandas as pd

team_name_arr = ["두산", "롯데", "삼성", "키움", "한화", "KIA", "KT", "LG", "NC", "SSG"]

select_month = 4
select_year = 2024

response = {}

for teamName in team_name_arr :
    team_df = pd.read_csv(f'./Data/rank/{teamName}_rank.csv')
    team_df = team_df.iloc[:, :3]
    team_df.columns = ['date', 'team', 'rank']
    team_df.date = pd.to_datetime(team_df.date)
    result_df = team_df[(team_df.date.dt.year == int(select_year)) & (team_df.date.dt.month == int(select_month))]
    result_df.date = result_df.date.astype(str)

    if teamName not in response.keys() :
        response[teamName] = []

    for i in range(len(result_df)) :
        response[teamName].append(result_df.iloc[i,:].to_dict())

response

/var/folders/q5/q667z4nj3mv72k7_1mqf5hd80000gn/T/ipykernel_28009/2205988287.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result_df.date = result_df.date.astype(str)
/var/folders/q5/q667z4nj3mv72k7_1mqf5hd80000gn/T/ipykernel_28009/2205988287.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result_df.date = result_df.date.astype(str)
/var/folders/q5/q667z4nj3mv72k7_1mqf5hd80000gn/T/ipykernel_28009/2205988287.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result_df.date = result_df.date.astype(str)
/var/folders/q5/q667z4nj3mv72k7_1mqf5hd80000gn/T/ipykernel_28009/2205988287.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result_df.date = result_df.date.astype(str)
/var/folders/q5/q667z4nj3mv72k7_1mqf5hd80000gn/T/ipykernel_28009/2205988287.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result_df.date = result_df.date.astype(str)
/var/folders/q5/q667z4nj3mv72k7_1mqf5hd80000gn/T/ipykernel_28009/2205988287.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result_df.date = result_df.date.astype(str)
/var/folders/q5/q667z4nj3mv72k7_1mqf5hd80000gn/T/ipykernel_28009/2205988287.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result_df.date = result_df.date.astype(str)
/var/folders/q5/q667z4nj3mv72k7_1mqf5hd80000gn/T/ipykernel_28009/2205988287.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result_df.date = result_df.date.astype(str)
/var/folders/q5/q667z4nj3mv72k7_1mqf5hd80000gn/T/ipykernel_28009/2205988287.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result_df.date = result_df.date.astype(str)
/var/folders/q5/q667z4nj3mv72k7_1mqf5hd80000gn/T/ipykernel_28009/2205988287.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result_df.date = result_df.date.astype(str)

{'두산': [{'date': '2024-04-02', 'team': '두산', 'rank': 6},
  {'date': '2024-04-03', 'team': '두산', 'rank': 7},
  {'date': '2024-04-04', 'team': '두산', 'rank': 7},
  {'date': '2024-04-05', 'team': '두산', 'rank': 7},
  {'date': '2024-04-06', 'team': '두산', 'rank': 7},
  {'date': '2024-04-07', 'team': '두산', 'rank': 7},
  {'date': '2024-04-09', 'team': '두산', 'rank': 7},
  {'date': '2024-04-10', 'team': '두산', 'rank': 7},
  {'date': '2024-04-11', 'team': '두산', 'rank': 8},
  {'date': '2024-04-12', 'team': '두산', 'rank': 8},
  {'date': '2024-04-13', 'team': '두산', 'rank': 7},
  {'date': '2024-04-14', 'team': '두산', 'rank': 7},
  {'date': '2024-04-16', 'team': '두산', 'rank': 8},
  {'date': '2024-04-17', 'team': '두산', 'rank': 8},
  {'date': '2024-04-18', 'team': '두산', 'rank': 8},
  {'date': '2024-04-19', 'team': '두산', 'rank': 8},
  {'date': '2024-04-20', 'team': '두산', 'rank': 8},
  {'date': '2024-04-21', 'team': '두산', 'rank': 8},
  {'date': '2024-04-23', 'team': '두산', 'rank': 7},
  {'date': '2024-04-24', 'team': '두산', 'rank': 7},
  {'date': '2024-04-25', 'team': '두산', 'rank': 7},
  {'date': '2024-04-26', 'team': '두산', 'rank': 7},
  {'date': '2024-04-27', 'team': '두산', 'rank': 7},
  {'date': '2024-04-28', 'team': '두산', 'rank': 6},
  {'date': '2024-04-30', 'team': '두산', 'rank': 6}],
 '롯데': [{'date': '2024-04-02', 'team': '롯데', 'rank': 8},
  {'date': '2024-04-03', 'team': '롯데', 'rank': 8},
  {'date': '2024-04-04', 'team': '롯데', 'rank': 8},
  {'date': '2024-04-05', 'team': '롯데', 'rank': 9},
  {'date': '2024-04-06', 'team': '롯데', 'rank': 8},
  {'date': '2024-04-07', 'team': '롯데', 'rank': 8},
  {'date': '2024-04-09', 'team': '롯데', 'rank': 9},
  {'date': '2024-04-10', 'team': '롯데', 'rank': 9},
  {'date': '2024-04-11', 'team': '롯데', 'rank': 9},
  {'date': '2024-04-12', 'team': '롯데', 'rank': 10},
  {'date': '2024-04-13', 'team': '롯데', 'rank': 10},
  {'date': '2024-04-14', 'team': '롯데', 'rank': 10},
  {'date': '2024-04-16', 'team': '롯데', 'rank': 10},
  {'date': '2024-04-17', 'team': '롯데', 'rank': 10},
  {'date': '2024-04-18', 'team': '롯데', 'rank': 10},
  {'date': '2024-04-19', 'team': '롯데', 'rank': 10},
  {'date': '2024-04-20', 'team': '롯데', 'rank': 10},
  {'date': '2024-04-21', 'team': '롯데', 'rank': 9},
  {'date': '2024-04-23', 'team': '롯데', 'rank': 10},
  {'date': '2024-04-24', 'team': '롯데', 'rank': 10},
  {'date': '2024-04-25', 'team': '롯데', 'rank': 10},
  {'date': '2024-04-26', 'team': '롯데', 'rank': 10},
  {'date': '2024-04-27', 'team': '롯데', 'rank': 10},
  {'date': '2024-04-28', 'team': '롯데', 'rank': 10},
  {'date': '2024-04-30', 'team': '롯데', 'rank': 10}],
 '삼성': [{'date': '2024-04-02', 'team': '삼성', 'rank': 8},
  {'date': '2024-04-03', 'team': '삼성', 'rank': 8},
  {'date': '2024-04-04', 'team': '삼성', 'rank': 8},
  {'date': '2024-04-05', 'team': '삼성', 'rank': 9},
  {'date': '2024-04-06', 'team': '삼성', 'rank': 8},
  {'date': '2024-04-07', 'team': '삼성', 'rank': 8},
  {'date': '2024-04-09', 'team': '삼성', 'rank': 8},
  {'date': '2024-04-10', 'team': '삼성', 'rank': 8},
  {'date': '2024-04-11', 'team': '삼성', 'rank': 7},
  {'date': '2024-04-12', 'team': '삼성', 'rank': 7},
  {'date': '2024-04-13', 'team': '삼성', 'rank': 8},
  {'date': '2024-04-14', 'team': '삼성', 'rank': 8},
  {'date': '2024-04-16', 'team': '삼성', 'rank': 7},
  {'date': '2024-04-17', 'team': '삼성', 'rank': 6},
  {'date': '2024-04-18', 'team': '삼성', 'rank': 5},
  {'date': '2024-04-19', 'team': '삼성', 'rank': 6},
  {'date': '2024-04-20', 'team': '삼성', 'rank': 5},
  {'date': '2024-04-21', 'team': '삼성', 'rank': 5},
  {'date': '2024-04-23', 'team': '삼성', 'rank': 3},
  {'date': '2024-04-24', 'team': '삼성', 'rank': 3},
  {'date': '2024-04-25', 'team': '삼성', 'rank': 3},
  {'date': '2024-04-26', 'team': '삼성', 'rank': 3},
  {'date': '2024-04-27', 'team': '삼성', 'rank': 3},
  {'date': '2024-04-28', 'team': '삼성', 'rank': 3},
  {'date': '2024-04-30', 'team': '삼성', 'rank': 3}],
 '키움': [{'date': '2024-04-02', 'team': '키움', 'rank': 7},
  {'date': '2024-04-03', 'team': '키움', 'rank': 6},
  {'date': '2024-04-04', 'team': '키움', 'rank': 6},
  {'date': '2024-04-05', 'team': '키움', 'rank': 5},
  {'date': '2024-04-06', 'team': '키움', 'rank': 5},
  {'date': '2024-04-07', 'team': '키움', 'rank': 3},
  {'date': '2024-04-09', 'team': '키움', 'rank': 4},
  {'date': '2024-04-10', 'team': '키움', 'rank': 4},
  {'date': '2024-04-11', 'team': '키움', 'rank': 4},
  {'date': '2024-04-12', 'team': '키움', 'rank': 3},
  {'date': '2024-04-13', 'team': '키움', 'rank': 3},
  {'date': '2024-04-14', 'team': '키움', 'rank': 3},
  {'date': '2024-04-16', 'team': '키움', 'rank': 2},
  {'date': '2024-04-17', 'team': '키움', 'rank': 3},
  {'date': '2024-04-18', 'team': '키움', 'rank': 4},
  {'date': '2024-04-19', 'team': '키움', 'rank': 4},
  {'date': '2024-04-20', 'team': '키움', 'rank': 4},
  {'date': '2024-04-21', 'team': '키움', 'rank': 3},
  {'date': '2024-04-23', 'team': '키움', 'rank': 5},
  {'date': '2024-04-24', 'team': '키움', 'rank': 5},
  {'date': '2024-04-25', 'team': '키움', 'rank': 6},
  {'date': '2024-04-26', 'team': '키움', 'rank': 6},
  {'date': '2024-04-27', 'team': '키움', 'rank': 6},
  {'date': '2024-04-28', 'team': '키움', 'rank': 7},
  {'date': '2024-04-30', 'team': '키움', 'rank': 7}],
 '한화': [{'date': '2024-04-02', 'team': '한화', 'rank': 1},
  {'date': '2024-04-03', 'team': '한화', 'rank': 1},
  {'date': '2024-04-04', 'team': '한화', 'rank': 1},
  {'date': '2024-04-05', 'team': '한화', 'rank': 2},
  {'date': '2024-04-06', 'team': '한화', 'rank': 2},
  {'date': '2024-04-07', 'team': '한화', 'rank': 4},
  {'date': '2024-04-09', 'team': '한화', 'rank': 5},
  {'date': '2024-04-10', 'team': '한화', 'rank': 5},
  {'date': '2024-04-11', 'team': '한화', 'rank': 5},
  {'date': '2024-04-12', 'team': '한화', 'rank': 5},
  {'date': '2024-04-13', 'team': '한화', 'rank': 5},
  {'date': '2024-04-14', 'team': '한화', 'rank': 5},
  {'date': '2024-04-16', 'team': '한화', 'rank': 5},
  {'date': '2024-04-17', 'team': '한화', 'rank': 7},
  {'date': '2024-04-18', 'team': '한화', 'rank': 7},
  {'date': '2024-04-19', 'team': '한화', 'rank': 6},
  {'date': '2024-04-20', 'team': '한화', 'rank': 7},
  {'date': '2024-04-21', 'team': '한화', 'rank': 7},
  {'date': '2024-04-23', 'team': '한화', 'rank': 8},
  {'date': '2024-04-24', 'team': '한화', 'rank': 8},
  {'date': '2024-04-25', 'team': '한화', 'rank': 8},
  {'date': '2024-04-26', 'team': '한화', 'rank': 8},
  {'date': '2024-04-27', 'team': '한화', 'rank': 8},
  {'date': '2024-04-28', 'team': '한화', 'rank': 8},
  {'date': '2024-04-30', 'team': '한화', 'rank': 8}],
 'KIA': [{'date': '2024-04-02', 'team': 'KIA', 'rank': 3},
  {'date': '2024-04-03', 'team': 'KIA', 'rank': 2},
  {'date': '2024-04-04', 'team': 'KIA', 'rank': 2},
  {'date': '2024-04-05', 'team': 'KIA', 'rank': 1},
  {'date': '2024-04-06', 'team': 'KIA', 'rank': 1},
  {'date': '2024-04-07', 'team': 'KIA', 'rank': 2},
  {'date': '2024-04-09', 'team': 'KIA', 'rank': 1},
  {'date': '2024-04-10', 'team': 'KIA', 'rank': 1},
  {'date': '2024-04-11', 'team': 'KIA', 'rank': 1},
  {'date': '2024-04-12', 'team': 'KIA', 'rank': 1},
  {'date': '2024-04-13', 'team': 'KIA', 'rank': 1},
  {'date': '2024-04-14', 'team': 'KIA', 'rank': 1},
  {'date': '2024-04-16', 'team': 'KIA', 'rank': 1},
  {'date': '2024-04-17', 'team': 'KIA', 'rank': 1},
  {'date': '2024-04-18', 'team': 'KIA', 'rank': 1},
  {'date': '2024-04-19', 'team': 'KIA', 'rank': 1},
  {'date': '2024-04-20', 'team': 'KIA', 'rank': 1},
  {'date': '2024-04-21', 'team': 'KIA', 'rank': 1},
  {'date': '2024-04-23', 'team': 'KIA', 'rank': 1},
  {'date': '2024-04-24', 'team': 'KIA', 'rank': 1},
  {'date': '2024-04-25', 'team': 'KIA', 'rank': 1},
  {'date': '2024-04-26', 'team': 'KIA', 'rank': 1},
  {'date': '2024-04-27', 'team': 'KIA', 'rank': 1},
  {'date': '2024-04-28', 'team': 'KIA', 'rank': 1},
  {'date': '2024-04-30', 'team': 'KIA', 'rank': 1}],
 'KT': [{'date': '2024-04-02', 'team': 'KT', 'rank': 10},
  {'date': '2024-04-03', 'team': 'KT', 'rank': 10},
  {'date': '2024-04-04', 'team': 'KT', 'rank': 10},
  {'date': '2024-04-05', 'team': 'KT', 'rank': 8},
  {'date': '2024-04-06', 'team': 'KT', 'rank': 10},
  {'date': '2024-04-07', 'team': 'KT', 'rank': 10},
  {'date': '2024-04-09', 'team': 'KT', 'rank': 10},
  {'date': '2024-04-10', 'team': 'KT', 'rank': 10},
  {'date': '2024-04-11', 'team': 'KT', 'rank': 10},
  {'date': '2024-04-12', 'team': 'KT', 'rank': 9},
  {'date': '2024-04-13', 'team': 'KT', 'rank': 9},
  {'date': '2024-04-14', 'team': 'KT', 'rank': 9},
  {'date': '2024-04-16', 'team': 'KT', 'rank': 9},
  {'date': '2024-04-17', 'team': 'KT', 'rank': 9},
  {'date': '2024-04-18', 'team': 'KT', 'rank': 9},
  {'date': '2024-04-19', 'team': 'KT', 'rank': 9},
  {'date': '2024-04-20', 'team': 'KT', 'rank': 9},
  {'date': '2024-04-21', 'team': 'KT', 'rank': 10},
  {'date': '2024-04-23', 'team': 'KT', 'rank': 9},
  {'date': '2024-04-24', 'team': 'KT', 'rank': 9},
  {'date': '2024-04-25', 'team': 'KT', 'rank': 9},
  {'date': '2024-04-26', 'team': 'KT', 'rank': 9},
  {'date': '2024-04-27', 'team': 'KT', 'rank': 9},
  {'date': '2024-04-28', 'team': 'KT', 'rank': 9},
  {'date': '2024-04-30', 'team': 'KT', 'rank': 9}],
 'LG': [{'date': '2024-04-02', 'team': 'LG', 'rank': 5},
  {'date': '2024-04-03', 'team': 'LG', 'rank': 5},
  {'date': '2024-04-04', 'team': 'LG', 'rank': 4},
  {'date': '2024-04-05', 'team': 'LG', 'rank': 6},
  {'date': '2024-04-06', 'team': 'LG', 'rank': 6},
  {'date': '2024-04-07', 'team': 'LG', 'rank': 4},
  {'date': '2024-04-09', 'team': 'LG', 'rank': 5},
  {'date': '2024-04-10', 'team': 'LG', 'rank': 5},
  {'date': '2024-04-11', 'team': 'LG', 'rank': 6},
  {'date': '2024-04-12', 'team': 'LG', 'rank': 5},
  {'date': '2024-04-13', 'team': 'LG', 'rank': 5},
  {'date': '2024-04-14', 'team': 'LG', 'rank': 5},
  {'date': '2024-04-16', 'team': 'LG', 'rank': 5},
  {'date': '2024-04-17', 'team': 'LG', 'rank': 5},
  {'date': '2024-04-18', 'team': 'LG', 'rank': 6},
  {'date': '2024-04-19', 'team': 'LG', 'rank': 5},
  {'date': '2024-04-20', 'team': 'LG', 'rank': 5},
  {'date': '2024-04-21', 'team': 'LG', 'rank': 5},
  {'date': '2024-04-23', 'team': 'LG', 'rank': 6},
  {'date': '2024-04-24', 'team': 'LG', 'rank': 6},
  {'date': '2024-04-25', 'team': 'LG', 'rank': 5},
  {'date': '2024-04-26', 'team': 'LG', 'rank': 5},
  {'date': '2024-04-27', 'team': 'LG', 'rank': 4},
  {'date': '2024-04-28', 'team': 'LG', 'rank': 5},
  {'date': '2024-04-30', 'team': 'LG', 'rank': 5}],
 'NC': [{'date': '2024-04-02', 'team': 'NC', 'rank': 2},
  {'date': '2024-04-03', 'team': 'NC', 'rank': 4},
  {'date': '2024-04-04', 'team': 'NC', 'rank': 4},
  {'date': '2024-04-05', 'team': 'NC', 'rank': 4},
  {'date': '2024-04-06', 'team': 'NC', 'rank': 2},
  {'date': '2024-04-07', 'team': 'NC', 'rank': 1},
  {'date': '2024-04-09', 'team': 'NC', 'rank': 2},
  {'date': '2024-04-10', 'team': 'NC', 'rank': 2},
  {'date': '2024-04-11', 'team': 'NC', 'rank': 2},
  {'date': '2024-04-12', 'team': 'NC', 'rank': 2},
  {'date': '2024-04-13', 'team': 'NC', 'rank': 2},
  {'date': '2024-04-14', 'team': 'NC', 'rank': 2},
  {'date': '2024-04-16', 'team': 'NC', 'rank': 3},
  {'date': '2024-04-17', 'team': 'NC', 'rank': 2},
  {'date': '2024-04-18', 'team': 'NC', 'rank': 2},
  {'date': '2024-04-19', 'team': 'NC', 'rank': 2},
  {'date': '2024-04-20', 'team': 'NC', 'rank': 2},
  {'date': '2024-04-21', 'team': 'NC', 'rank': 2},
  {'date': '2024-04-23', 'team': 'NC', 'rank': 2},
  {'date': '2024-04-24', 'team': 'NC', 'rank': 2},
  {'date': '2024-04-25', 'team': 'NC', 'rank': 2},
  {'date': '2024-04-26', 'team': 'NC', 'rank': 2},
  {'date': '2024-04-27', 'team': 'NC', 'rank': 2},
  {'date': '2024-04-28', 'team': 'NC', 'rank': 2},
  {'date': '2024-04-30', 'team': 'NC', 'rank': 2}],
 'SSG': [{'date': '2024-04-02', 'team': 'SSG', 'rank': 4},
  {'date': '2024-04-03', 'team': 'SSG', 'rank': 3},
  {'date': '2024-04-04', 'team': 'SSG', 'rank': 3},
  {'date': '2024-04-05', 'team': 'SSG', 'rank': 3},
  {'date': '2024-04-06', 'team': 'SSG', 'rank': 4},
  {'date': '2024-04-07', 'team': 'SSG', 'rank': 6},
  {'date': '2024-04-09', 'team': 'SSG', 'rank': 3},
  {'date': '2024-04-10', 'team': 'SSG', 'rank': 3},
  {'date': '2024-04-11', 'team': 'SSG', 'rank': 3},
  {'date': '2024-04-12', 'team': 'SSG', 'rank': 4},
  {'date': '2024-04-13', 'team': 'SSG', 'rank': 4},
  {'date': '2024-04-14', 'team': 'SSG', 'rank': 4},
  {'date': '2024-04-16', 'team': 'SSG', 'rank': 4},
  {'date': '2024-04-17', 'team': 'SSG', 'rank': 4},
  {'date': '2024-04-18', 'team': 'SSG', 'rank': 3},
  {'date': '2024-04-19', 'team': 'SSG', 'rank': 3},
  {'date': '2024-04-20', 'team': 'SSG', 'rank': 3},
  {'date': '2024-04-21', 'team': 'SSG', 'rank': 4},
  {'date': '2024-04-23', 'team': 'SSG', 'rank': 3},
  {'date': '2024-04-24', 'team': 'SSG', 'rank': 3},
  {'date': '2024-04-25', 'team': 'SSG', 'rank': 3},
  {'date': '2024-04-26', 'team': 'SSG', 'rank': 3},
  {'date': '2024-04-27', 'team': 'SSG', 'rank': 4},
  {'date': '2024-04-28', 'team': 'SSG', 'rank': 4},
  {'date': '2024-04-30', 'team': 'SSG', 'rank': 4}]}

          date teamname  rank
334 2024-04-02      SSG     4
335 2024-04-03      SSG     3
336 2024-04-04      SSG     3
337 2024-04-05      SSG     3
338 2024-04-06      SSG     4
339 2024-04-07      SSG     6
340 2024-04-09      SSG     3
341 2024-04-10      SSG     3
342 2024-04-11      SSG     3
343 2024-04-12      SSG     4
344 2024-04-13      SSG     4
345 2024-04-14      SSG     4
346 2024-04-16      SSG     4
347 2024-04-17      SSG     4
348 2024-04-18      SSG     3
349 2024-04-19      SSG     3
350 2024-04-20      SSG     3
351 2024-04-21      SSG     4
352 2024-04-23      SSG     3
353 2024-04-24      SSG     3
354 2024-04-25      SSG     3
355 2024-04-26      SSG     3
356 2024-04-27      SSG     4
357 2024-04-28      SSG     4
358 2024-04-30      SSG     4

/var/folders/q5/q667z4nj3mv72k7_1mqf5hd80000gn/T/ipykernel_28009/443445062.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result_df.date = result_df.date.astype(str)

{'date': '2024-04-02', 'teamname': 'SSG', 'rank': 4}
{'date': '2024-04-03', 'teamname': 'SSG', 'rank': 3}
{'date': '2024-04-04', 'teamname': 'SSG', 'rank': 3}
{'date': '2024-04-05', 'teamname': 'SSG', 'rank': 3}
{'date': '2024-04-06', 'teamname': 'SSG', 'rank': 4}
{'date': '2024-04-07', 'teamname': 'SSG', 'rank': 6}
{'date': '2024-04-09', 'teamname': 'SSG', 'rank': 3}
{'date': '2024-04-10', 'teamname': 'SSG', 'rank': 3}
{'date': '2024-04-11', 'teamname': 'SSG', 'rank': 3}
{'date': '2024-04-12', 'teamname': 'SSG', 'rank': 4}
{'date': '2024-04-13', 'teamname': 'SSG', 'rank': 4}
{'date': '2024-04-14', 'teamname': 'SSG', 'rank': 4}
{'date': '2024-04-16', 'teamname': 'SSG', 'rank': 4}
{'date': '2024-04-17', 'teamname': 'SSG', 'rank': 4}
{'date': '2024-04-18', 'teamname': 'SSG', 'rank': 3}
{'date': '2024-04-19', 'teamname': 'SSG', 'rank': 3}
{'date': '2024-04-20', 'teamname': 'SSG', 'rank': 3}
{'date': '2024-04-21', 'teamname': 'SSG', 'rank': 4}
{'date': '2024-04-23', 'teamname': 'SSG', 'rank': 3}
{'date': '2024-04-24', 'teamname': 'SSG', 'rank': 3}
{'date': '2024-04-25', 'teamname': 'SSG', 'rank': 3}
{'date': '2024-04-26', 'teamname': 'SSG', 'rank': 3}
{'date': '2024-04-27', 'teamname': 'SSG', 'rank': 4}
{'date': '2024-04-28', 'teamname': 'SSG', 'rank': 4}
{'date': '2024-04-30', 'teamname': 'SSG', 'rank': 4}